#!/bin/bash
# Name: negate_xbm.sh
# Author: Rob Toscani
# Date: 11th of June 2025
# Description: This script produces the negative of an .xbm image file and sends the output
# to stdout. Purpose is to compensate a CDE backdrop image (.xbm format) in case it flips
# to the negative if shown in certain colors by the 'xbackdrop' program by Alexander
# Pampuchin (part of the 'Enhanced Motif Window Manager (EMWM)' - https://fastestcode.org/
# - LGPLv3, MIT License).
#
#######################################################################################
#
# Copyright (C) 2025 Rob Toscani <rob_toscani@yahoo.com>
#
# negate_xbm.sh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# negate_xbm.sh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
####################################################################################


xbmfile=$1

echo "/* NEGATIVE OF EXISTING .XBM FILE, GENERATED BY NEGATE_XBM.SH (R.J.TOSCANI) */"
grep -v "0x" $xbmfile


grep "0x" $xbmfile |
tr  ',' '\n'       |
sed 's/0x//g'      |
sed 's/};//g'      |

while read hex; do

    [[ $hex == "" ]] && continue
    printf "%X\n" $((255-16#$hex))   # Flip the 0 and 1 bits in binary representation

done                             |

sed 's/^/\t0x/g'                 |
tr  '[[:upper:]]' '[[:lower:]]'  |
tr  '\n' ','                     |
sed -E 's/(([^,]+,){12})/\1\n/g'

echo "};"
